Add the option of automatically registering irrigations using an automated hydrometer
openmeteo/aira pull request #315
Opened 2020-08-29 20:38 UTC by AbdullahKady

I have added environment variables to the settings since the keys are private.

1) I didn't add any tests yet, in case my approach is wrong or needs to be drastically changed, so not to waste the effort.
2) There are a couple of `TODO` comments in the `tasks.py` file which I'd think would be best to be reviewed first, these comments should be removed within the PR, just waiting for your input.

2020-09-22 07:19 UTC, aptiko requested changes
Sorry for the delay in reviewing. I made several comments, but I haven't been exhaustive, since I think some kind of redesign is needed.

2020-09-22 07:19 UTC, aptiko commented on aira/tasks.py
> +    """
Please follow PEP 257.

I think that much of the rest of this file should be methods in `TelemetricFlowmeter` (or subclasses of it). This task could be something like

    for flowmeter in TelemetricFlowmeter.objects.all():
        flowmeter.get_irrigations()

I don't really know. From what I've seen so far, inheritance looks like the best solution, but I don't really know. But whether with inheritance or with a JSONField or something else, I think that we should improve on this design.

2020-09-22 07:19 UTC, aptiko commented on requirements.txt
> +requests==2.24.0
Use `requests>=2.21,<3`.

The `2.21` is because the version currently prepackaged for Debian is 2.21. In many cases we might want to use that if there's no reason to use a more recent one.

I know this is not a very good idea, and the apps often break because of a change in a version of a dependency, but this is what we've been doing until now, so until we decide to change it, let's be consistent.

2020-09-22 07:19 UTC, aptiko commented on aira/templates/aira/create_telemetricflowmeter/main.html
> +    */
I think this doesn't apply any more.

BTW, I have now implemented some JS unit tests with jest:

    npm install
    npm run lint
    npm run test

(You might need to run `nvm install 10` first if your node version isn't recent enough.)

2020-10-08 09:16 UTC, AbdullahKady commented on aira/models.py
> +    is_flowmeter_reported = models.BooleanField(
Not really in my opinion, maybe `is_automatically_reported`? 
because I think the reporting is the automated part, not the measurement. Also I feel like `is/should_xyz` is a regularly used convention in naming boolean attributes in general, even in native methods (`isinstance`, `isdecimal`, etc.).

2020-10-08 09:18 UTC, AbdullahKady commented on aira/models.py
> +        ]
What I had in mind was the three attributes, I definitely missed the core one (`agrifield`) :sweat_smile: 
Adding the water volume is just a sanity addition in case 2 points happen to be reported at the same time with different values.

2020-10-10 20:29 UTC, AbdullahKady commented on aira/templates/aira/create_telemetricflowmeter/main.html
> +    */
I checked the configuration, I think currently the introduction of node is for testing and linting only, right?
As in no module bundling (so I cannot import JS files etc.).

2020-10-10 20:47 UTC, AbdullahKady commented
@aptiko Thank you for the review! I started with multi-table inheritance but I then stopped it because it didn't make sense since the parent `Flowmeter` shouldn't actually exist as an entity by itself (only children should be created), so I just used normal python inheritance (`abstract = True`).

I think you'll need to try this locally to see how the form works, but a quick screenshot might give you an idea, the view supports multiple forms that can be toggled through the dropdown on-the-fly through JS, and the user submits the selected form, which is validated normally and saved. The following screenshot might make a bit of sense:
![Screenshot from 2020-10-10 22-43-04](https://user-images.githubusercontent.com/15708438/95664633-fcfeb080-0b49-11eb-8698-84328462ef31.png)



1) I think you'll need to run `makemessages`, aside from newly introduced messages, you might -potentially- find some message(s) missing due to conflict-resolving when I pulled master (sorry :sweat_smile:)
2) I still didn't write tests, just needed your opinion first to avoid wasting time if something isn't right
3) You didn't mention anything about viewing/updating existing flowmeter entry for an `agrifield`, will this be included, and if so what are the details
4) I wanted to know you approach for reporting sanity errors (that shouldn't happen, at least to our knowledge so far), in this PR's case, it's TTN returning flowmeters that are not registered in the system, do you have any error aggregations (i.e. should I use `logger.error`), or should I just fail silently

2020-10-15 07:14 UTC, aptiko commented on aira/models.py
> +    is_flowmeter_reported = models.BooleanField(
OK. I'd name it `is_measured_automatically`, but it's your code, and `is_automatically_reported` is also OK.

2020-10-15 07:15 UTC, aptiko commented on aira/templates/aira/create_telemetricflowmeter/main.html
> +    */
That's right, for the time being I'm only using node to lint and test.

2020-10-15 10:07 UTC, aptiko commented
BTW, I think that what you call "normal python inheritance" is a Django feature called "inheritance with abstract base classes". Yes, multi-table inheritance is a pain and it's better to use abstract base classes when it's possible.

1. Why are you bothering with translations? I can make them afterwards. And, BTW, how have you made these translations?
2. I have several observations, but they all concern details. Overall I like it. I think you can proceed with unit testing and we'll fix the details afterwards.
3. I think that currently the user can view and edit applied irrigations. There should be no difference with automated flowmeters; again the user should be able to view them (but there should be an indication that these particular records are automatically ~measured~ reported) and edit them; but if he edits them, `is_automatically_reported` should be cleared.
4. I think it's a good idea to log the problem. We do have a log file in production but I don't remember if anything is currently ever written to it or the mechanism with which it works. There's a standard way to log something with Django and it's configured in the settings I think? If yes, use that standard way.

BTW, I generally think that modules named `utils.py` or similar are undesirable. Sometimes you can't avoid them, but they're often an indication of not having given enough thought on how to organize the code. In this particular case, I think you don't need `group_by_key_value()` at all—you can achieve the same thing with `itertools.groupby()`:

```python
def _request_the_things_network_digest(since="1d"):
    # ...
    filtered_data.sort(key=lambda x: x["device_id"])
    return itertools.groupby(filtered_data, key=lambda x: x["device_id"])
```

2020-10-15 11:02 UTC, AbdullahKady commented
@aptiko Yes indeed, I meant "behaving as normal inheritance", as in nothing is reflected in the DB, just simply the attributes being inherited.

1) No I didn't do anything with the translations, these are yours from the previous iteration (when we had them view-only without an actual model), I was saying the po files might have been messed up when merging/pulling master.
2) :ok_hand: 
3) Technically they're view-able currently, the point is, I don't highlight if it's automatically reported. The question is, what approach should I take for this? 2 lists to show the irrigations depending on their type? or show them all together with a checkmark icon or something denoting whether or not it was automatically added?
4) Okay, will just use python's logging module.

Finally, will check the utils part, didn't know there is an existing functionality for that tbh.

2020-10-15 12:16 UTC, aptiko commented
For (3), use a single list with a checkmark or something.

2020-10-25 23:03 UTC, AbdullahKady commented
@aptiko sorry for the late update .. 
Celery is error'ing tasks for me as so: `TypeError: calculate_crop_evapotranspiration() got an unexpected keyword argument 'kc_plantingdate'`. Not sure what that's about, but a fresh master checkout still has the same issue, so most probably a problem with my setup.

- I tried your `itertools` solution, it didn't really achieve the expected behavior, so I added a test for the expected parsing, so that changing the implementation will be easy for you (i.e. a bit of confidence won't hurt)
- In views tests, I'm a bit lost on what and how to test. If we need to test the multi-form functionality, I think it will be a bit excessive in terms of testing effort, so I'd like your opinion regarding that

2020-11-18 15:59 UTC, aptiko commented
Superseded by #377.

2020-11-18 15:59 UTC, closed without merging